# Data paths
data:
  # base_path: "topk_data/amazon14"
  # item_mappings: "target_item_mapping.csv"
  # test_samples: "amz_14_final_samples.csv"
  # topk_list: "amz-topk_iid_list.pkl"
  # topk_scores: "amz-topk_score.pkl"
  base_path: "topk_data/movielens"
  item_mappings: "target_item_mapping.csv"
  test_samples: "test_samples.csv"
  topk_list: "ml-topk_iid_list.pkl"
  topk_scores: "ml-topk_score.pkl"
  movie_categories: "movie_categories.csv"

# Embedder settings
embedder:
  model_name: "all-MiniLM-L6-v2"
  device: "cuda"
  batch_size: 40960

# Experiment parameters
experiment:
  # Available diversifiers:
  # - motley (param: theta_)
  # - mmr (param: lambda_)
  # - bswap (param: theta_)
  # - clt (param: lambda_)
  # - msd (param: lambda_)
  # - swap (param: theta_)
  # - sy (param: lambda_)
  diversifier: "motley"
  param_name: "theta_"   # Parameter name is auto-set based on diversifier if not specified
  param_start: 0.0
  param_end: 1.0
  param_step: 0.05
  threshold_drop: 0.1
  top_k: 10 
  use_category_ild: true