# Data paths
data:
  base_path: "topk_data/movielens"
  item_mappings: "target_item_mapping.csv"
  test_samples: "test_samples.csv"
  topk_list: "ml-topk_iid_list.pkl"
  topk_scores: "ml-topk_score.pkl"
  movie_categories: "movie_categories.csv"

# Embedder settings
embedder:
  # model_name: "all-MiniLM-L6-v2"
  model_name: "intfloat/multilingual-e5-large"
  device: "cuda"
  batch_size: 40960

# Experiment parameters
experiment:
  diversifier: "mmr"
  param_name: "lambda_"
  param_start: 0.0
  param_end: 1.0
  param_step: 0.005
  threshold_drop: 0.1
  top_k: 10
  use_category_ild: true

# Similarity scores settings
similarity:
  use_similarity_scores: false
  similarity_scores_path: "/mnt/scratch1/byilmaz/data_syn/similarity_results.pkl"
