# Data paths
data:
  base_path: "topk_data/movielens"
  item_mappings: "target_item_mapping.csv"
  test_samples: "test_samples.csv"
  topk_list: "ml-topk_iid_list.pkl"
  topk_scores: "ml-topk_score.pkl"
  movie_categories: "movie_categories.csv"  # Optional: only for category-based ILD

# Embedder settings
embedder:
  model_name: "all-MiniLM-L6-v2"
  device: "cpu"
  batch_size: 40960

# Algorithm configurations
algorithms:
  motley:
    param_name: "theta_"
    param_start: 0.0
    param_end: 1.0
    param_step: 0.05
    threshold_drop: 0.01
    top_k: 10

  mmr:
    param_name: "lambda_"
    param_start: 0.0
    param_end: 1.0
    param_step: 0.05
    threshold_drop: 0.01
    top_k: 10

  bswap:
    param_name: "theta_"
    param_start: 0.0
    param_end: 1.0
    param_step: 0.05
    threshold_drop: 0.01
    top_k: 10

  clt:
    param_name: "lambda_"
    param_start: 0.0
    param_end: 1.0
    param_step: 0.05
    threshold_drop: 0.01
    top_k: 10
    pick_strategy: "medoid"  # or "highest_relevance"

  msd:
    param_name: "lambda_"
    param_start: 0.0
    param_end: 1.0
    param_step: 0.05
    threshold_drop: 0.01
    top_k: 10

  swap:
    param_name: "theta_"
    param_start: 0.0
    param_end: 1.0
    param_step: 0.05
    threshold_drop: 0.01
    top_k: 10

  sy:
    param_name: "threshold"
    param_start: 1.0
    param_end: 0.0
    param_step: -0.05
    threshold_drop: 0.01
    top_k: 10
